### PR TITLE
Better handling of the output parts, Remote run space support. DSL experiments

### PR DESCRIPTION
**Pull request by jhoneill**
I've changed 5 functions - details in changelog.md 
* Getting output parts of the cells back in Get-NotebookContent and using them in `ConvertFrom-Notebook`. 
* Add support for magic commands, non-stream data and verbose output in add-notebookCode
* Support Multiple notebook kernel types in New-PSNotebooks, support existing (remote) runspace 
* Fiddle with aliases so there is a DSL style of 
```
notebook -inc {
   code $foo; 
   markdown $bar
} -dotnet file.ipynb 
```

The combination of aliases and remoting allows this 
```
$pssession =  New-PSSession -ComputerName $computername  -

notebook {
    markdown  "# Run Remotely on $computername"
    NotebookContent  .\template.ipynb | foreach {&  $_.Type   $_.Source }
}  -IncludeCodeResults  -DNI  "$computerName.ipynb" -RunSpace $pssession.Runspace

Remove-PSSession $pssession
```
Make a session,  for each cell in a template either output its markdown or run its code in the session's runspace, output to a new file.

### CODE REVIEW

**Comment by dfinke** [comment]
@jhoneill I didn't check the CI issues. Anything obvious to you?

**Comment by dfinke** [comment]
These are great, really like the direction. Would you be able to add more tests for things like the Get-NotebookContent?

**Comment by dfinke** [comment]
@jhoneill. Needed to add a couple functions to the psd1 export functions. 

The `Test-HasParameterizedCell` function uses `Get-NotebookContent` with the `-PassThru` switch. I think I saw you removed it. Not sure how to fix this yet.

I needed all the json returned so I could search the metadata tags too, that's where the `parameters` tag is stored.

Found this when running the tests.

image

**Comment by jhoneill** [comment]
> @jhoneill. Needed to add a couple functions to the psd1 export functions.
> 
> The `Test-HasParameterizedCell` function uses `Get-NotebookContent` with the `-PassThru` switch. I think I saw you removed it. Not sure how to fix this yet.
> 
> I needed all the json returned so I could search the metadata tags too, that's where the `parameters` tag is stored.

I think that's fixed. All the test run anyway.
 Not sure how / why I took pass through out. I can only guess that a removed the `if (passthru) {return stuff}`  by accident and tidied up the parameter later. It's an odd thing to have done.

**Comment by dfinke** [comment]
In `Get-Notebook` it doesn't look like the URL part is set up fully.

**Pull request merged**
